### ISSUE TITLE
Should WebTransportSendStream and WebTransportReceiveStream be transferable?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webtransport#424] opened 2022-10-06 00:59 UTC
For almost a year, between #307 and #395 (nevermind #423), the following streams were [transferable streams](https://streams.spec.whatwg.org/#transferrable-streams):
```js
let {readable, writable} = await wt.createBidirectionalStream();

writable = await wt.createUnidirectionalStream();

for await (readable of wt.incomingUnidirectionalStreams)
```
But right now they're not, [since](https://html.spec.whatwg.org/multipage/structured-data.html#transferable-objects) _"[Platform objects](https://webidl.spec.whatwg.org/#dfn-platform-object) can be [transferable objects](https://html.spec.whatwg.org/multipage/structured-data.html#transferable-objects) if their [primary interface](https://webidl.spec.whatwg.org/#dfn-primary-interface) is decorated with the [Transferable] IDL [extended attribute](https://webidl.spec.whatwg.org/#dfn-extended-attribute)."_

Q: Should they be? This would allow `.getStats()` to be called where data is read and written, as well as make this allowed:

```js
const wt = new WebTransport(url);
const {readable, writable} = await wt.createBidirectionalStream();
sendWorker.postMessage({writable}, [writable]);
receiveWorker.postMessage({readable}, [readable]);
```
If we don't then the above will fail, and apps would have to work around it like this instead instead:
```js
const wt = new WebTransport(url);
const wts = await wt.createBidirectionalStream();
const sendable = new TransformStream(), receivable = new TransformStream();
sendable.pipeTo(wts.writable);
wts.readable.pipeTo(receivable.writable);
sendWorker.postMessage({sendable}, [sendable]);
receiveWorker.postMessage({receivable}, [receivable]);
```

**Comment by aboba** [comment] 2022-10-06 14:28
I was hoping to avoid the `pipeTo` workarounds you describe.  For example, being able to transfer the readable stream `wt.incomingUnidirectionalStreams` would be helpful.

**Comment by aboba** [comment] 2022-10-07 00:46
I seem to have confirmed that attempting to transfer `wt.incomingUndirectionalStreams` does work.  The error is `A ReadableStream could not be cloned because it was not transferred.` On the positive side, on main thread it seems possible to construct a WebTransport then build a 'complex' readable or writable stream based on it, and then transfer those streams to (distinct) workers. I wasn't expecting that to work....

**Comment by ricea** [comment] 2022-10-07 11:11
> When `getReader()` is called on the transferred readable stream of streams, the error is `A ReadableStream could not be cloned because it was not transferred.`

Sorry about this. Currently when a stream is transferred, the chunks that are passed through the stream are always cloned, never transferred. Since `incomingUnidirectionalStreams` is a stream of streams, each chunk is a stream, and streams can only be transferred, not cloned.

There was a plan to also support transferring the chunks (see [Future Work](https://github.com/whatwg/streams/blob/main/transferable-streams-explainer.md#future-work)) but without a concrete use case it never proceeded to the design stage.

**Comment by aboba** [comment] 2022-10-07 17:18
Tried out constructing readable and writable streams on main thread and then transferring them to the receiveWorker and sendWorker, respectively.  The performance is bad (frame latencies of 1700 ms as compared with 100 ms with a single worker).  Also, the tab crashes. 

I'm transferring the readable and writable streams directly, rather than constructing dummy transfer streams as Jan-Ivar suggested and then using pipeTo.  Maybe that's the problem? 

The (quite broken) sample is [here](https://webrtc.internaut.com/wc/wtSender6/).

**Closed** 2022-12-01 21:19 UTC
Labels: Ready for PR
