### ISSUE TITLE
Keep connection on tab switch

### ISSUE THREAD

**Issue by simbleau** [w3c/webtransport#600] opened 2024-04-17 22:13 UTC
Something that has us with our heads spinning is why webtransport closes connections currently in Chrome when the user switches tabs. 

This is contrary to web sockets, which are scoped to the browser instead of a tab.

It's important for many use cases, e.g.
- Listening to streamed audio on a different tab
- Not getting disconnected on a web game when switching tabs

Should this be underscored as a standard for downstream implementers, e.g. Chrome / Firefox?

**Comment by jan-ivar** [comment] 2024-04-17 22:51
Hi simbleau, are you sure the connection is closed and not merely throttled?

> Something that has us with our heads spinning is why webtransport closes connections currently in Chrome when the user switches tabs.

What do you mean by "user switches tabs"? If you're seeing Chrome drop connections from a document no longer having [focus](https://html.spec.whatwg.org/multipage/interaction.html#focus) or no longer being [visible](https://html.spec.whatwg.org/multipage/interaction.html#visibility-state), then that sounds like an implementation bug, and you should file an issue with that vendor.

Both WebSocket and WebTransport connections are tied to the [Document](https://html.spec.whatwg.org/multipage/dom.html#document) (webpage), whose lifetime is generally understood to survive tab switching, so there should be no need to call it out in this spec.



@vasilvv I wonder could the background webpage be experiencing throttling?

**Comment by MOZGIII** [comment] 2024-04-17 23:19
As part of our discussion at the https://github.com/cBournhonesque/lightyear/issues/144 the issue we might be facing is a combination of the losing tab focus and [Chrome's Energy Saving][1] functionality, which would, it seems like, unload the `Document`, thus losing the WebTransport session.
As a workaround for this, we've explored playing audio on the tab to prevent its eviction.

[1]: https://blog.google/products/chrome/new-chrome-features-to-save-battery-and-make-browsing-smoother/

To me it seems like things like Energy Saving should also be standardized, or at least their behaviour should be understood and explicitly accounted for in the standards.
Maybe we need a "Wake Lock" API for explicitly keeping contexts alive.

**Comment by martinthomson** [comment] 2024-04-18 01:41
Wake lock only works because the site is visible and therefore somewhat accountable to the user as a result.  Having a way for background tabs to keep themselves alive indefinitely without any sort of feedback would not be a desirable outcome.

A more elegant way to signal a pending (and maybe then imminent) interruption of service might still work.

**Comment by ricea** [comment] 2024-04-19 05:16
For some use cases, closing the WebTransport when the page becomes hidden and reopening it when it becomes visible again may be an adequate workaround. See https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event

If this is a Chromium-specific issue, you could try filing a bug at https://crbug.com/.

**Comment by jan-ivar** [comment] 2024-04-24 14:12
@simbleau are you able to reproduce this in Firefox? If not, I suggest closing this and opening an issue on chromium.

**Comment by simbleau** [comment] 2024-04-24 14:14
Well, I can't find a way to test on Firefox, it doesn't work for me at all. I get connection rejected errors because self signed certs aren't accepted.

Do you know of a good way to test this on FF?

**Comment by simbleau** [comment] 2024-04-24 15:01
> @simbleau - if you run this simple example https://webrtc.internaut.com/wt/ on a Chrome tab, connect, send some data, than switch to another tab, come back, in my testing you can resume sending data, meaning that the underlying WebTransport connection was not closed. Do you get the same behavior?

Hm, that works on both browsers for me.

The only difference I can think of is that in our implementation, we poll WebTransport consistently from WebAssembly.

Perhaps this is an issue of our own? @MOZGIII @cBournhonesque

**Comment by jan-ivar** [comment] 2024-05-08 14:47
> Well, I can't find a way to test on Firefox, it doesn't work for me at all. I get connection rejected errors because self signed certs aren't accepted.

Self-signed certs [should be supported in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1806693). Please [file an issue](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Networking%3A%20HTTP) on Firefox with your symptoms.

**Comment by wilaw** [comment] 2024-05-08 14:50
Closing as we don't believe this is an issue with the web API. Both WebSocket and WebTransport connections are tied to the [Document](https://html.spec.whatwg.org/multipage/dom.html#document) (webpage), whose lifetime is generally understood to survive tab switching, so there should be no need to call this out explicitly in this spec. Please reopen if you still feel that a spec change is required.

**Closed by wilaw** 2024-05-08 14:50 UTC
